## code generation
# FLASHSTART=0x0
RAMSTART=0x30010000
# WATCHDOG=1

include makefile_inc

target: target-m33
	

# include special-rule.mk.internal if existing - for Lauterbach internal usage
-include special-rule.mk.internal

