set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_SYSROOT $ENV{SDKTARGETSYSROOT})
set(CMAKE_STAGING_PREFIX /home/devel/stage)

set(tools $ENV{OECORE_NATIVE_SYSROOT}/usr/bin/aarch64-poky-linux)
set(CMAKE_PREFIX aarch64-poky-linux-)
set(CMAKE_C_COMPILER ${tools}/${CMAKE_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${tools}/${CMAKE_PREFIX}g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

