/* ${REA_DISCLAIMER_PLACEHOLDER} */

#ifndef BSP_IRQ_ID_H
#define BSP_IRQ_ID_H

/***********************************************************************************************************************
 * Macro definitions
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Typedef definitions
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Exported global variables
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Exported global functions (to be accessed by other files)
 **********************************************************************************************************************/

/*******************************************************************************************************************
 * @addtogroup BSP_MPU_RZG2L
 * @{
 **********************************************************************************************************************/

typedef enum IRQn {
    Reset_IRQn                  = -15,
    NonMaskableInt_IRQn         = -14,
    HardFault_IRQn              = -13,
    MemoryManagement_IRQn       = -12,
    BusFault_IRQn               = -11,
    UsageFault_IRQn             = -10,
    SecureFault_IRQn            = -9,
    SVCall_IRQn                 = -5,
    DebugMonitor_IRQn           = -4,
    PendSV_IRQn                 = -2,
    SysTick_IRQn                = -1,

    NMI_IRQn                    = 0,    /* Interrupt ID:0,  NMI         */
    GPIO_IRQ0_IRQn              = 1,    /* Interrupt ID:1,  IRQ0        */
    GPIO_IRQ1_IRQn              = 2,    /* Interrupt ID:2,  IRQ1        */
    GPIO_IRQ2_IRQn              = 3,    /* Interrupt ID:3,  IRQ2        */
    GPIO_IRQ3_IRQn              = 4,    /* Interrupt ID:4,  IRQ3        */
    GPIO_IRQ4_IRQn              = 5,    /* Interrupt ID:5,  IRQ4        */
    GPIO_IRQ5_IRQn              = 6,    /* Interrupt ID:6,  IRQ5        */
    GPIO_IRQ6_IRQn              = 7,    /* Interrupt ID:7,  IRQ6        */
    GPIO_IRQ7_IRQn              = 8,    /* Interrupt ID:8,  IRQ7        */
    COMM_IRQ1_IRQn              = 9,    /* Interrupt ID:9,  nCOMMIRQ[1] */
    COMM_IRQ0_IRQn              = 10,   /* Interrupt ID:10, nCOMMIRQ[0] */
    PMU_IRQ1_IRQn               = 11,   /* Interrupt ID:11, nPMUIRQ[1]  */
    PMU_IRQ0_IRQn               = 12,   /* Interrupt ID:12, nPMUIRQ[0]  */
    CLUSTER_PMU_IRQn            = 13,   /* Interrupt ID:13, nCLUSTERPMUIRQ */
    ERR_IRQ2_IRQn               = 14,   /* Interrupt ID:14, nERRIRQ[2] */
    ERR_IRQ1_IRQn               = 15,   /* Interrupt ID:15, nERRIRQ[1] */
    ERR_IRQ0_IRQn               = 16,   /* Interrupt ID:16, nERRIRQ[0] */
    FAULT_IRQ2_IRQn             = 17,   /* Interrupt ID:17, nFAULTIRQ[2] */
    FAULT_IRQ1_IRQn             = 18,   /* Interrupt ID:18, nFAULTIRQ[1] */
    FAULT_IRQ0_IRQn             = 19,   /* Interrupt ID:19, nFAULTIRQ[0] */
    CTI_IRQ1_IRQn               = 20,   /* Interrupt ID:20, CTIIRQ[1] */
    CTI_IRQ0_IRQn               = 21,   /* Interrupt ID:21, CTIIRQ[0] */
    FAULT_INT_IRQn              = 22,   /* Interrupt ID:22, fault_int */
    ERR_INT_IRQn                = 23,   /* Interrupt ID:23, err_int */
    PMU_INT_IRQn                = 24,   /* Interrupt ID:24, pmu_int */
    BUS_ERR_INTR_W_SXCA55_IRQn  = 25,   /* Interrupt ID:25, BUS_ERR_INTR_W_SXCA55 */
    TZCINT_SRAM_A_IRQn          = 26,   /* Interrupt ID:26, TZCINT_SRAM_A */
    TZCINT_SRAM_M_IRQn          = 27,   /* Interrupt ID:27, TZCINT_SRAM_M */
    TZCINT_SPI_IRQn             = 28,   /* Interrupt ID:28, TZCINT_SPI */
    TZCINT_DDR_IRQn             = 29,   /* Interrupt ID:29, TZCINT_DDR */
    ERRINT_BRG_CM33_S_IRQn      = 30,   /* Interrupt ID:30, ERRINT_BRG_CM33_S */
    ERRINT_BRG_CM33_C_IRQn      = 31,   /* Interrupt ID:31, ERRINT_BRG_CM33_C */
    SECINT_IRQn                 = 32,   /* Interrupt ID:32, SECINT */
    DEDINT_IRQn                 = 33,   /* Interrupt ID:33, DEDINT */
    ACPU_EC7TIE1_IRQn           = 34,   /* Interrupt ID:34, ACPU EC7TIE1[0] */
    ACPU_EC7TIE2_IRQn           = 35,   /* Interrupt ID:35, ACPU EC7TIE2[0] */
    ACPU_EC7TIOVF_IRQn          = 36,   /* Interrupt ID:36, ACPU EC7TIOVF[0] */
    MCPU_EC7TIE1_IRQn           = 37,   /* Interrupt ID:37, MCPU EC7TIE1[0] */
    MCPU_EC7TIE2_IRQn           = 38,   /* Interrupt ID:38, MCPU EC7TIE2[0] */
    MCPU_EC7TIOVF_IRQn          = 39,   /* Interrupt ID:39, MCPU EC7TIOVF[0] */
    DDR_CONTROLL_IRQn           = 40,   /* Interrupt ID:40, DDR3L/4 Interrupt signal from the controller */
    SPI_MULTI_IRQn              = 41,   /* Interrupt ID:41, SPI Multi interrupt request signal */
    SYS_LPM_INT_IRQn            = 42,   /* Interrupt ID:42, SYS_LPM_INT */
    SYS_CA55STBYDONE_INT_IRQn   = 43,   /* Interrupt ID:43, SYS_CA55STBYDONE_INT */
    SYS_CM33STBYR_INT_IRQn      = 44,   /* Interrupt ID:44, SYS_CM33STBYR_INT */
    SYS_CA55_DENY_IRQn          = 45,   /* Interrupt ID:45, SYS_CA55_DENY */
    GTM0_IRQn                   = 46,   /* Interrupt ID:46, General Timer ch 0 Interrupt signal */
    GTM1_IRQn                   = 47,   /* Interrupt ID:47, General Timer ch 1 Interrupt signal */
    GTM2_IRQn                   = 48,   /* Interrupt ID:48, General Timer ch 2 Interrupt signal */
    CA55_CORE0_WDTINT_IRQn      = 49,   /* Interrupt ID:49, CA55 core 0 WDTINT  */
    CA55_CORE0_PERROUT_IRQn     = 50,   /* Interrupt ID:50, CA55 core 0 PERROUT */
    CA55_CORE1_WDTINT_IRQn      = 51,   /* Interrupt ID:51, CA55 core 1 WDTINT  */
    CA55_CORE1_PERROUT_IRQn     = 52,   /* Interrupt ID:52, CA55 core 1 PERROUT */
    CM33_WDTINT_IRQn            = 53,   /* Interrupt ID:53, CM33 WDTINT  */
    CM33_PERROUT_IRQn           = 54,   /* Interrupt ID:54, CM33 PERROUT */
    POWER_WDTINT_IRQn           = 55,   /* Interrupt ID:55, Power up WDTINT */
    MSG0_S_IRQn                 = 56,   /* Interrupt ID:56, msg_ch0_s */
    MSG1_S_IRQn                 = 57,   /* Interrupt ID:57, msg_ch1_s */
    MSG2_S_IRQn                 = 58,   /* Interrupt ID:58, msg_ch2_s */
    MSG3_S_IRQn                 = 59,   /* Interrupt ID:59, msg_ch3_s */
    MSG4_S_IRQn                 = 60,   /* Interrupt ID:60, msg_ch4_s */
    MSG5_S_IRQn                 = 61,   /* Interrupt ID:61, msg_ch5_s */
    RSP0_S_IRQn                 = 62,   /* Interrupt ID:62, rsp_ch0_s */
    RSP1_S_IRQn                 = 63,   /* Interrupt ID:63, rsp_ch1_s */
    RSP2_S_IRQn                 = 64,   /* Interrupt ID:64, rsp_ch2_s */
    RSP3_S_IRQn                 = 65,   /* Interrupt ID:65, rsp_ch3_s */
    RSP4_S_IRQn                 = 66,   /* Interrupt ID:66, rsp_ch4_s */
    RSP5_S_IRQn                 = 67,   /* Interrupt ID:67, rsp_ch5_s */
    MSG0_NS_IRQn                = 68,   /* Interrupt ID:68, msg_ch0_ns */
    MSG1_NS_IRQn                = 69,   /* Interrupt ID:69, msg_ch1_ns */
    MSG2_NS_IRQn                = 70,   /* Interrupt ID:70, msg_ch2_ns */
    MSG3_NS_IRQn                = 71,   /* Interrupt ID:71, msg_ch3_ns */
    MSG4_NS_IRQn                = 72,   /* Interrupt ID:72, msg_ch4_ns */
    MSG5_NS_IRQn                = 73,   /* Interrupt ID:73, msg_ch5_ns */
    RSP0_NS_IRQn                = 74,   /* Interrupt ID:74, rsp_ch0_ns */
    RSP1_NS_IRQn                = 75,   /* Interrupt ID:75, rsp_ch1_ns */
    RSP2_NS_IRQn                = 76,   /* Interrupt ID:76, rsp_ch2_ns */
    RSP3_NS_IRQn                = 77,   /* Interrupt ID:77, rsp_ch3_ns */
    RSP4_NS_IRQn                = 78,   /* Interrupt ID:78, rsp_ch4_ns */
    RSP5_NS_IRQn                = 79,   /* Interrupt ID:79, rsp_ch5_ns */
    SW_MHU_INT0_IRQn            = 80,   /* Interrupt ID:80, sw_mhu_int_0 */
    SW_MHU_INT1_IRQn            = 81,   /* Interrupt ID:81, sw_mhu_int_1 */
    SW_MHU_INT2_IRQn            = 82,   /* Interrupt ID:82, sw_mhu_int_2 */
    SW_MHU_INT3_IRQn            = 83,   /* Interrupt ID:83, sw_mhu_int_3 */
    ETH0_PIF_INT_IRQn           = 84,   /* Interrupt ID:84, pif_int_n */
    ETH0_FIL_INT_IRQn           = 85,   /* Interrupt ID:85, int_fil_n */
    ETH0_ARP_NS_IRQn            = 86,   /* Interrupt ID:86, int_arp_ns_n */
    ETH1_PIF_INT_IRQn           = 87,   /* Interrupt ID:87, pif_int_n */
    ETH1_FIL_INT_IRQn           = 88,   /* Interrupt ID:88, int_fil_n */
    ETH1_ARP_NS_IRQn            = 89,   /* Interrupt ID:89, int_arp_ns_n */
    U2H0_INT_IRQn               = 90,   /* Interrupt ID:90, U2H0_INT */
    U2H0_OHCI_INT_IRQn          = 91,   /* Interrupt ID:91, U2H0_OHCI_INT */
    U2H0_EHCI_INT_IRQn          = 92,   /* Interrupt ID:92, U2H0_EHCI_INT */
    U2H0_WAKEON_INT_IRQn        = 93,   /* Interrupt ID:93, U2H0_WAKEON_INT */
    U2H0_OBINT_IRQn             = 94,   /* Interrupt ID:94, U2H0_OBINT */
    U2H1_INT_IRQn               = 95,   /* Interrupt ID:95, U2H1_INT */
    U2H1_OHCI_INT_IRQn          = 96,   /* Interrupt ID:96, U2H1_OHCI_INT */
    U2H1_EHCI_INT_IRQn          = 97,   /* Interrupt ID:97, U2H1_EHCI_INT */
    U2H1_WAKEON_INT_IRQn        = 98,   /* Interrupt ID:98, U2H1_WAKEON_INT */
    U2H1_OBINT_IRQn             = 99,   /* Interrupt ID:99, U2H1_OBINT */
    U2P_IXL_INT_IRQn            = 100,  /* Interrupt ID:100, U2P_IXL_INT */
    U2P_INT_DMA0_IRQn           = 101,  /* Interrupt ID:101, U2P_INT_DMA[0] */
    U2P_INT_DMA1_IRQn           = 102,  /* Interrupt ID:102, U2P_INT_DMA[1] */
    U2P_INT_DMAERR_IRQn         = 103,  /* Interrupt ID:103, U2P_INT_DMAERR */
    SDHI_eMMC0_OXMN_IRQn        = 104,  /* Interrupt ID:104, SDHI_eMMC0 OXMNIRQ */
    SDHI_eMMC0_OXASIO_IRQn      = 105,  /* Interrupt ID:105, SDHI_eMMC0 OXASIOIRQ */
    SDHI_eMMC1_OXMN_IRQn        = 106,  /* Interrupt ID:106, SDHI_eMMC1 OXMNIRQ */
    SDHI_eMMC1_OXASIO_IRQn      = 107,  /* Interrupt ID:107, SDHI_eMMC1 OXASIOIRQ */
    DMAC_INT0_S_IRQn            = 108,  /* Interrupt ID:108, DMAC_intreq_dmaint0(Secure) */
    DMAC_INT1_S_IRQn            = 109,  /* Interrupt ID:109, DMAC_intreq_dmaint1(Secure) */
    DMAC_INT2_S_IRQn            = 110,  /* Interrupt ID:110, DMAC_intreq_dmaint2(Secure) */
    DMAC_INT3_S_IRQn            = 111,  /* Interrupt ID:111, DMAC_intreq_dmaint3(Secure) */
    DMAC_INT4_S_IRQn            = 112,  /* Interrupt ID:112, DMAC_intreq_dmaint4(Secure) */
    DMAC_INT5_S_IRQn            = 113,  /* Interrupt ID:113, DMAC_intreq_dmaint5(Secure) */
    DMAC_INT6_S_IRQn            = 114,  /* Interrupt ID:114, DMAC_intreq_dmaint6(Secure) */
    DMAC_INT7_S_IRQn            = 115,  /* Interrupt ID:115, DMAC_intreq_dmaint7(Secure) */
    DMAC_INT8_S_IRQn            = 116,  /* Interrupt ID:116, DMAC_intreq_dmaint8(Secure) */
    DMAC_INT9_S_IRQn            = 117,  /* Interrupt ID:117, DMAC_intreq_dmaint9(Secure) */
    DMAC_INT10_S_IRQn           = 118,  /* Interrupt ID:118, DMAC_intreq_dmaint10(Secure) */
    DMAC_INT11_S_IRQn           = 119,  /* Interrupt ID:119, DMAC_intreq_dmaint11(Secure) */
    DMAC_INT12_S_IRQn           = 120,  /* Interrupt ID:120, DMAC_intreq_dmaint12(Secure) */
    DMAC_INT13_S_IRQn           = 121,  /* Interrupt ID:121, DMAC_intreq_dmaint13(Secure) */
    DMAC_INT14_S_IRQn           = 122,  /* Interrupt ID:122, DMAC_intreq_dmaint14(Secure) */
    DMAC_INT15_S_IRQn           = 123,  /* Interrupt ID:123, DMAC_intreq_dmaint15(Secure) */
    DMAERR_S_IRQn               = 124,  /* Interrupt ID:124, DMAERR(Secure) */
    DMAC_INT0_NS_IRQn           = 125,  /* Interrupt ID:125, DMAC_intreq_dmaint0(Non-Secure) */
    DMAC_INT1_NS_IRQn           = 126,  /* Interrupt ID:126, DMAC_intreq_dmaint1(Non-Secure) */
    DMAC_INT2_NS_IRQn           = 127,  /* Interrupt ID:127, DMAC_intreq_dmaint2(Non-Secure) */
    DMAC_INT3_NS_IRQn           = 128,  /* Interrupt ID:128, DMAC_intreq_dmaint3(Non-Secure) */
    DMAC_INT4_NS_IRQn           = 129,  /* Interrupt ID:129, DMAC_intreq_dmaint4(Non-Secure) */
    DMAC_INT5_NS_IRQn           = 130,  /* Interrupt ID:130, DMAC_intreq_dmaint5(Non-Secure) */
    DMAC_INT6_NS_IRQn           = 131,  /* Interrupt ID:131, DMAC_intreq_dmaint6(Non-Secure) */
    DMAC_INT7_NS_IRQn           = 132,  /* Interrupt ID:132, DMAC_intreq_dmaint7(Non-Secure) */
    DMAC_INT8_NS_IRQn           = 133,  /* Interrupt ID:133, DMAC_intreq_dmaint8(Non-Secure) */
    DMAC_INT9_NS_IRQn           = 134,  /* Interrupt ID:134, DMAC_intreq_dmaint9(Non-Secure) */
    DMAC_INT10_NS_IRQn          = 135,  /* Interrupt ID:135, DMAC_intreq_dmaint10(Non-Secure) */
    DMAC_INT11_NS_IRQn          = 136,  /* Interrupt ID:136, DMAC_intreq_dmaint11(Non-Secure) */
    DMAC_INT12_NS_IRQn          = 137,  /* Interrupt ID:137, DMAC_intreq_dmaint12(Non-Secure) */
    DMAC_INT13_NS_IRQn          = 138,  /* Interrupt ID:138, DMAC_intreq_dmaint13(Non-Secure) */
    DMAC_INT14_NS_IRQn          = 139,  /* Interrupt ID:139, DMAC_intreq_dmaint14(Non-Secure) */
    DMAC_INT15_NS_IRQn          = 140,  /* Interrupt ID:140, DMAC_intreq_dmaint15(Non-Secure) */
    DMAERR_NS_IRQn              = 141,  /* Interrupt ID:141, DMAERR(Non-Secure) */
    DSI_INT_SEQ0_IRQn           = 142,  /* Interrupt ID:142, dsi_int_seq0 */
    DSI_INT_SEQ1_IRQn           = 143,  /* Interrupt ID:143, dsi_int_seq1 */
    DSI_INT_VIN1_IRQn           = 144,  /* Interrupt ID:144, dsi_int_vin1 */
    DSI_INT_RVC_IRQn            = 145,  /* Interrupt ID:145, dsi_int_rcv */
    DSI_INT_FERR_IRQn           = 146,  /* Interrupt ID:146, dsi_int_ferr */
    DSI_INT_PPI_IRQn            = 147,  /* Interrupt ID:147, dsi_int_ppi */
    DSI_INT_DEBUG_IRQn          = 148,  /* Interrupt ID:148, dsi_int_debug */
    VSLO_INTREQ_IRQn            = 149,  /* Interrupt ID:149, vs1o_intreq_n */
    VSLO_SMG0_UNMATCH_IRQn      = 150,  /* Interrupt ID:150, vs1o_smg0_int_unmatched_n */
    VSLO_SMG0_FROZEN_IRQn       = 151,  /* Interrupt ID:151, vs1o_smg0_int_frozen_n */
    DUO_INTR_IRQn               = 152,  /* Interrupt ID:152, duo_intr_n */
    MALIG31_GPU_IRQn            = 153,  /* Interrupt ID:153, IRQGPU */
    MALIG31_JOB_IRQn            = 154,  /* Interrupt ID:154, IRQJOB */
    MALIG31_MMU_IRQn            = 155,  /* Interrupt ID:155, IRQMMU */
    MALIG31_EVT_IRQn            = 156,  /* Interrupt ID:156, IRQEVENT */
    ISU_INT_FRE_IRQn            = 157,  /* Interrupt ID:157, ISU_INT_FRE */
    ISU_INT_DESE_IRQn           = 158,  /* Interrupt ID:158, ISU_INT_DESE */
    ISU_INT_STOPE_IRQn          = 159,  /* Interrupt ID:159, ISU_INT_STOPE */
    ISU_INT_ERR_IRQn            = 160,  /* Interrupt ID:160, ISU_INT_ERR */
    H264_VPO_VINTREQ_IRQn       = 161,  /* Interrupt ID:161, vpo_vintreq_n */
    H264_VPO_CINTREQ_IRQn       = 162,  /* Interrupt ID:162, vpo_cintreq_n */
    H264_VPO_VEDCERR_IRQn       = 163,  /* Interrupt ID:163, vpo_vedcerr */
    H264_VPO_CEDCERR_IRQn       = 164,  /* Interrupt ID:164, vpo_cedcerr */
    H264_FCO_EDCERR_IRQn        = 165,  /* Interrupt ID:165, fco_edcerr */
    CRU_CSI2_LINK_INT_IRQn      = 166,  /* Interrupt ID:166, csi2_link_int  */
    CRU_IMAGE_CONV_INT_IRQn     = 167,  /* Interrupt ID:167, image_conv_int */
    CRU_IMAGE_CONV_ERR_INT_IRQn = 168,  /* Interrupt ID:168, image_conv_err_int */
    AXI_MST_ERR_IRQn            = 169,  /* Interrupt ID:169, axi_mst_err_int */
    MTU_TGI0A_PLS_IRQn          = 170,  /* Interrupt ID:170, tgi0a_pls_n */
    MTU_TGI0B_PLS_IRQn          = 171,  /* Interrupt ID:171, tgi0b_pls_n */
    MTU_TGI0C_PLS_IRQn          = 172,  /* Interrupt ID:172, tgi0c_pls_n */
    MTU_TGI0D_PLS_IRQn          = 173,  /* Interrupt ID:173, tgi0d_pls_n */
    MTU_TGI0V_PLS_IRQn          = 174,  /* Interrupt ID:174, tci0v_pls_n */
    MTU_TGI0E_PLS_IRQn          = 175,  /* Interrupt ID:175, tgi0e_pls_n */
    MTU_TGI0F_PLS_IRQn          = 176,  /* Interrupt ID:176, tgi0f_pls_n */
    MTU_TGI1A_PLS_IRQn          = 177,  /* Interrupt ID:177, tgi1a_pls_n */
    MTU_TGI1B_PLS_IRQn          = 178,  /* Interrupt ID:178, tgi1b_pls_n */
    MTU_TGI1V_PLS_IRQn          = 179,  /* Interrupt ID:179, tci1v_pls_n */
    MTU_TGI1U_PLS_IRQn          = 180,  /* Interrupt ID:180, tci1u_pls_n */
    MTU_TGI2A_PLS_IRQn          = 181,  /* Interrupt ID:181, tgi2a_pls_n */
    MTU_TGI2B_PLS_IRQn          = 182,  /* Interrupt ID:182, tgi2b_pls_n */
    MTU_TGI2V_PLS_IRQn          = 183,  /* Interrupt ID:183, tci2v_pls_n */
    MTU_TGI2U_PLS_IRQn          = 184,  /* Interrupt ID:184, tci2u_pls_n */
    MTU_TGI3A_PLS_IRQn          = 185,  /* Interrupt ID:185, tgi3ai_pls_n */
    MTU_TGI3B_PLS_IRQn          = 186,  /* Interrupt ID:186, tgi3bi_pls_n */
    MTU_TGI3C_PLS_IRQn          = 187,  /* Interrupt ID:187, tgi3ci_pls_n */
    MTU_TGI3D_PLS_IRQn          = 188,  /* Interrupt ID:188, tgi3di_pls_n */
    MTU_TGI3V_PLS_IRQn          = 189,  /* Interrupt ID:189, tci3vi_pls_n */
    MTU_TGI4A_PLS_IRQn          = 190,  /* Interrupt ID:190, tgi4ai_pls_n */
    MTU_TGI4B_PLS_IRQn          = 191,  /* Interrupt ID:191, tgi4bi_pls_n */
    MTU_TGI4C_PLS_IRQn          = 192,  /* Interrupt ID:192, tgi4ci_pls_n */
    MTU_TGI4D_PLS_IRQn          = 193,  /* Interrupt ID:193, tgi4di_pls_n */
    MTU_TGI4V_PLS_IRQn          = 194,  /* Interrupt ID:194, tci4vi_pls_n */
    MTU_TGI5U_PLS_IRQn          = 195,  /* Interrupt ID:195, tgi5ui_pls_n */
    MTU_TGI5V_PLS_IRQn          = 196,  /* Interrupt ID:196, tgi5vi_pls_n */
    MTU_TGI5W_PLS_IRQn          = 197,  /* Interrupt ID:197, tgi5wi_pls_n */
    MTU_TGI6A_PLS_IRQn          = 198,  /* Interrupt ID:198, tgi6ai_pls_n */
    MTU_TGI6B_PLS_IRQn          = 199,  /* Interrupt ID:199, tgi6bi_pls_n */
    MTU_TGI6C_PLS_IRQn          = 200,  /* Interrupt ID:200, tgi6ci_pls_n */
    MTU_TGI6D_PLS_IRQn          = 201,  /* Interrupt ID:201, tgi6di_pls_n */
    MTU_TGI6V_PLS_IRQn          = 202,  /* Interrupt ID:202, tci6vi_pls_n */
    MTU_TGI7A_PLS_IRQn          = 203,  /* Interrupt ID:203, tgi7ai_pls_n */
    MTU_TGI7B_PLS_IRQn          = 204,  /* Interrupt ID:204, tgi7bi_pls_n */
    MTU_TGI7C_PLS_IRQn          = 205,  /* Interrupt ID:205, tgi7ci_pls_n */
    MTU_TGI7D_PLS_IRQn          = 206,  /* Interrupt ID:206, tgi7di_pls_n */
    MTU_TGI7V_PLS_IRQn          = 207,  /* Interrupt ID:207, tci7vi_pls_n */
    MTU_TGI8A_PLS_IRQn          = 208,  /* Interrupt ID:208, tgi8a_pls_n */
    MTU_TGI8B_PLS_IRQn          = 209,  /* Interrupt ID:209, tgi8b_pls_n */
    MTU_TGI8C_PLS_IRQn          = 210,  /* Interrupt ID:210, tgi8c_pls_n */
    MTU_TGI8D_PLS_IRQn          = 211,  /* Interrupt ID:211, tgi8d_pls_n */
    MTU_TGI8V_PLS_IRQn          = 212,  /* Interrupt ID:212, tci8v_pls_n */
    MTU_TGI8U_PLS_IRQn          = 213,  /* Interrupt ID:213, tci8u_pls_n */
    POE3_OEI1_IRQn              = 214,  /* Interrupt ID:214, poe_oei1_n */
    POE3_OEI2_IRQn              = 215,  /* Interrupt ID:215, poe_oei2_n */
    POE3_OEI3_IRQn              = 216,  /* Interrupt ID:216, poe_oei3_n */
    POE3_OEI4_IRQn              = 217,  /* Interrupt ID:217, poe_oei4_n */
    GPT_GTCIA_0_IRQn            = 218,  /* Interrupt ID:218, gpt_gtcia_n[0] */
    GPT_GTCIB_0_IRQn            = 219,  /* Interrupt ID:219, gpt_gtcib_n[0] */
    GPT_GTCIC_0_IRQn            = 220,  /* Interrupt ID:220, gpt_gtcic_n[0] */
    GPT_GTCID_0_IRQn            = 221,  /* Interrupt ID:221, gpt_gtcid_n[0] */
    GPT_GTCIE_0_IRQn            = 222,  /* Interrupt ID:222, gpt_gtcie_n[0] */
    GPT_GTCIF_0_IRQn            = 223,  /* Interrupt ID:223, gpt_gtcif_n[0] */
    GPT_GTCIADA_0_IRQn          = 224,  /* Interrupt ID:224, gpt_gtciada_n[0] */
    GPT_GTCIADB_0_IRQn          = 225,  /* Interrupt ID:225, gpt_gtciadb_n[0] */
    GPT_GTCIV_0_IRQn            = 226,  /* Interrupt ID:226, gpt_gtciv_n[0] */
    GPT_GTCIU_0_IRQn            = 227,  /* Interrupt ID:227, gpt_gtciu_n[0] */
    GPT_GTCIH_0_IRQn            = 228,  /* Interrupt ID:228, gpt_gtcih_n[0] */
    GPT_GTCIL_0_IRQn            = 229,  /* Interrupt ID:229, gpt_gtcil_n[0] */
    GPT_GTDEI_0_IRQn            = 230,  /* Interrupt ID:230, gpt_gtdei_n[0] */
    GPT_GTCIA_1_IRQn            = 231,  /* Interrupt ID:231, gpt_gtcia_n[1] */
    GPT_GTCIB_1_IRQn            = 232,  /* Interrupt ID:232, gpt_gtcib_n[1] */
    GPT_GTCIC_1_IRQn            = 233,  /* Interrupt ID:233, gpt_gtcic_n[1] */
    GPT_GTCID_1_IRQn            = 234,  /* Interrupt ID:234, gpt_gtcid_n[1] */
    GPT_GTCIE_1_IRQn            = 235,  /* Interrupt ID:235, gpt_gtcie_n[1] */
    GPT_GTCIF_1_IRQn            = 236,  /* Interrupt ID:236, gpt_gtcif_n[1] */
    GPT_GTCIADA_1_IRQn          = 237,  /* Interrupt ID:237, gpt_gtciada_n[1] */
    GPT_GTCIADB_1_IRQn          = 238,  /* Interrupt ID:238, gpt_gtciadb_n[1] */
    GPT_GTCIV_1_IRQn            = 239,  /* Interrupt ID:239, gpt_gtciv_n[1] */
    GPT_GTCIU_1_IRQn            = 240,  /* Interrupt ID:240, gpt_gtciu_n[1] */
    GPT_GTCIH_1_IRQn            = 241,  /* Interrupt ID:241, gpt_gtcih_n[1] */
    GPT_GTCIL_1_IRQn            = 242,  /* Interrupt ID:242, gpt_gtcil_n[1] */
    GPT_GTDEI_1_IRQn            = 243,  /* Interrupt ID:243, gpt_gtdei_n[1] */
    GPT_GTCIA_2_IRQn            = 244,  /* Interrupt ID:244, gpt_gtcia_n[2] */
    GPT_GTCIB_2_IRQn            = 245,  /* Interrupt ID:245, gpt_gtcib_n[2] */
    GPT_GTCIC_2_IRQn            = 246,  /* Interrupt ID:246, gpt_gtcic_n[2] */
    GPT_GTCID_2_IRQn            = 247,  /* Interrupt ID:247, gpt_gtcid_n[2] */
    GPT_GTCIE_2_IRQn            = 248,  /* Interrupt ID:248, gpt_gtcie_n[2] */
    GPT_GTCIF_2_IRQn            = 249,  /* Interrupt ID:249, gpt_gtcif_n[2] */
    GPT_GTCIADA_2_IRQn          = 250,  /* Interrupt ID:250, gpt_gtciada_n[2] */
    GPT_GTCIADB_2_IRQn          = 251,  /* Interrupt ID:251, gpt_gtciadb_n[2] */
    GPT_GTCIV_2_IRQn            = 252,  /* Interrupt ID:252, gpt_gtciv_n[2] */
    GPT_GTCIU_2_IRQn            = 253,  /* Interrupt ID:253, gpt_gtciu_n[2] */
    GPT_GTCIH_2_IRQn            = 254,  /* Interrupt ID:254, gpt_gtcih_n[2] */
    GPT_GTCIL_2_IRQn            = 255,  /* Interrupt ID:255, gpt_gtcil_n[2] */
    GPT_GTDEI_2_IRQn            = 256,  /* Interrupt ID:256, gpt_gtdei_n[2] */
    GPT_GTCIA_3_IRQn            = 257,  /* Interrupt ID:257, gpt_gtcia_n[3] */
    GPT_GTCIB_3_IRQn            = 258,  /* Interrupt ID:258, gpt_gtcib_n[3] */
    GPT_GTCIC_3_IRQn            = 259,  /* Interrupt ID:259, gpt_gtcic_n[3] */
    GPT_GTCID_3_IRQn            = 260,  /* Interrupt ID:260, gpt_gtcid_n[3] */
    GPT_GTCIE_3_IRQn            = 261,  /* Interrupt ID:261, gpt_gtcie_n[3] */
    GPT_GTCIF_3_IRQn            = 262,  /* Interrupt ID:262, gpt_gtcif_n[3] */
    GPT_GTCIADA_3_IRQn          = 263,  /* Interrupt ID:263, gpt_gtciada_n[3] */
    GPT_GTCIADB_3_IRQn          = 264,  /* Interrupt ID:264, gpt_gtciadb_n[3] */
    GPT_GTCIV_3_IRQn            = 265,  /* Interrupt ID:265, gpt_gtciv_n[3] */
    GPT_GTCIU_3_IRQn            = 266,  /* Interrupt ID:266, gpt_gtciu_n[3] */
    GPT_GTCIH_3_IRQn            = 267,  /* Interrupt ID:267, gpt_gtcih_n[3] */
    GPT_GTCIL_3_IRQn            = 268,  /* Interrupt ID:268, gpt_gtcil_n[3] */
    GPT_GTDEI_3_IRQn            = 269,  /* Interrupt ID:269, gpt_gtdei_n[3] */
    GPT_GTCIA_4_IRQn            = 270,  /* Interrupt ID:270, gpt_gtcia_n[4] */
    GPT_GTCIB_4_IRQn            = 271,  /* Interrupt ID:271, gpt_gtcib_n[4] */
    GPT_GTCIC_4_IRQn            = 272,  /* Interrupt ID:272, gpt_gtcic_n[4] */
    GPT_GTCID_4_IRQn            = 273,  /* Interrupt ID:273, gpt_gtcid_n[4] */
    GPT_GTCIE_4_IRQn            = 274,  /* Interrupt ID:274, gpt_gtcie_n[4] */
    GPT_GTCIF_4_IRQn            = 275,  /* Interrupt ID:275, gpt_gtcif_n[4] */
    GPT_GTCIADA_4_IRQn          = 276,  /* Interrupt ID:276, gpt_gtciada_n[4] */
    GPT_GTCIADB_4_IRQn          = 277,  /* Interrupt ID:277, gpt_gtciadb_n[4] */
    GPT_GTCIV_4_IRQn            = 278,  /* Interrupt ID:278, gpt_gtciv_n[4] */
    GPT_GTCIU_4_IRQn            = 279,  /* Interrupt ID:279, gpt_gtciu_n[4] */
    GPT_GTCIH_4_IRQn            = 280,  /* Interrupt ID:280, gpt_gtcih_n[4] */
    GPT_GTCIL_4_IRQn            = 281,  /* Interrupt ID:281, gpt_gtcil_n[4] */
    GPT_GTDEI_4_IRQn            = 282,  /* Interrupt ID:282, gpt_gtdei_n[4] */
    GPT_GTCIA_5_IRQn            = 283,  /* Interrupt ID:283, gpt_gtcia_n[5] */
    GPT_GTCIB_5_IRQn            = 284,  /* Interrupt ID:284, gpt_gtcib_n[5] */
    GPT_GTCIC_5_IRQn            = 285,  /* Interrupt ID:285, gpt_gtcic_n[5] */
    GPT_GTCID_5_IRQn            = 286,  /* Interrupt ID:286, gpt_gtcid_n[5] */
    GPT_GTCIE_5_IRQn            = 287,  /* Interrupt ID:287, gpt_gtcie_n[5] */
    GPT_GTCIF_5_IRQn            = 288,  /* Interrupt ID:288, gpt_gtcif_n[5] */
    GPT_GTCIADA_5_IRQn          = 289,  /* Interrupt ID:289, gpt_gtciada_n[5] */
    GPT_GTCIADB_5_IRQn          = 290,  /* Interrupt ID:290, gpt_gtciadb_n[5] */
    GPT_GTCIV_5_IRQn            = 291,  /* Interrupt ID:291, gpt_gtciv_n[5] */
    GPT_GTCIU_5_IRQn            = 292,  /* Interrupt ID:292, gpt_gtciu_n[5] */
    GPT_GTCIH_5_IRQn            = 293,  /* Interrupt ID:293, gpt_gtcih_n[5] */
    GPT_GTCIL_5_IRQn            = 294,  /* Interrupt ID:294, gpt_gtcil_n[5] */
    GPT_GTDEI_5_IRQn            = 295,  /* Interrupt ID:295, gpt_gtdei_n[5] */
    GPT_GTCIA_6_IRQn            = 296,  /* Interrupt ID:296, gpt_gtcia_n[6] */
    GPT_GTCIB_6_IRQn            = 297,  /* Interrupt ID:297, gpt_gtcib_n[6] */
    GPT_GTCIC_6_IRQn            = 298,  /* Interrupt ID:298, gpt_gtcic_n[6] */
    GPT_GTCID_6_IRQn            = 299,  /* Interrupt ID:299, gpt_gtcid_n[6] */
    GPT_GTCIE_6_IRQn            = 300,  /* Interrupt ID:300, gpt_gtcie_n[6] */
    GPT_GTCIF_6_IRQn            = 301,  /* Interrupt ID:301, gpt_gtcif_n[6] */
    GPT_GTCIADA_6_IRQn          = 302,  /* Interrupt ID:302, gpt_gtciada_n[6] */
    GPT_GTCIADB_6_IRQn          = 303,  /* Interrupt ID:303, gpt_gtciadb_n[6] */
    GPT_GTCIV_6_IRQn            = 304,  /* Interrupt ID:304, gpt_gtciv_n[6] */
    GPT_GTCIU_6_IRQn            = 305,  /* Interrupt ID:305, gpt_gtciu_n[6] */
    GPT_GTCIH_6_IRQn            = 306,  /* Interrupt ID:306, gpt_gtcih_n[6] */
    GPT_GTCIL_6_IRQn            = 307,  /* Interrupt ID:307, gpt_gtcil_n[6] */
    GPT_GTDEI_6_IRQn            = 308,  /* Interrupt ID:308, gpt_gtdei_n[6] */
    GPT_GTCIA_7_IRQn            = 309,  /* Interrupt ID:309, gpt_gtcia_n[7] */
    GPT_GTCIB_7_IRQn            = 310,  /* Interrupt ID:310, gpt_gtcib_n[7] */
    GPT_GTCIC_7_IRQn            = 311,  /* Interrupt ID:311, gpt_gtcic_n[7] */
    GPT_GTCID_7_IRQn            = 312,  /* Interrupt ID:312, gpt_gtcid_n[7] */
    GPT_GTCIE_7_IRQn            = 313,  /* Interrupt ID:313, gpt_gtcie_n[7] */
    GPT_GTCIF_7_IRQn            = 314,  /* Interrupt ID:314, gpt_gtcif_n[7] */
    GPT_GTCIADA_7_IRQn          = 315,  /* Interrupt ID:315, gpt_gtciada_n[7] */
    GPT_GTCIADB_7_IRQn          = 316,  /* Interrupt ID:316, gpt_gtciadb_n[7] */
    GPT_GTCIV_7_IRQn            = 317,  /* Interrupt ID:317, gpt_gtciv_n[7] */
    GPT_GTCIU_7_IRQn            = 318,  /* Interrupt ID:318, gpt_gtciu_n[7] */
    GPT_GTCIH_7_IRQn            = 319,  /* Interrupt ID:319, gpt_gtcih_n[7] */
    GPT_GTCIL_7_IRQn            = 320,  /* Interrupt ID:320, gpt_gtcil_n[7] */
    GPT_GTDEI_7_IRQn            = 321,  /* Interrupt ID:321, gpt_gtdei_n[7] */
    POEGA_IRQn                  = 322,  /* Interrupt ID:322, mhc_elcoutdis */
    POEGB_IRQn                  = 323,  /* Interrupt ID:323, mhc_elcoutdis */
    POEGC_IRQn                  = 324,  /* Interrupt ID:324, mhc_elcoutdis */
    POEGD_IRQn                  = 325,  /* Interrupt ID:325, mhc_elcoutdis */
    I2S0_INT_REQ_IRQn           = 326,  /* Interrupt ID:326, INT_ssif_int_req */
    I2S0_DMA_RX_IRQn            = 327,  /* Interrupt ID:327, INT_ssif_dma_rx */
    I2S0_DMA_TX_IRQn            = 328,  /* Interrupt ID:328, INT_ssif_dma_tx */
    I2S0_DMA_RT_IRQn            = 329,  /* Interrupt ID:329, INT_ssif_dma_rt */
    I2S1_INT_REQ_IRQn           = 330,  /* Interrupt ID:330, INT_ssif_int_req */
    I2S1_DMA_RX_IRQn            = 331,  /* Interrupt ID:331, INT_ssif_dma_rx */
    I2S1_DMA_TX_IRQn            = 332,  /* Interrupt ID:332, INT_ssif_dma_tx */
    I2S1_DMA_RT_IRQn            = 333,  /* Interrupt ID:333, INT_ssif_dma_rt */
    I2S2_INT_REQ_IRQn           = 334,  /* Interrupt ID:334, INT_ssif_int_req */
    I2S2_DMA_RX_IRQn            = 335,  /* Interrupt ID:335, INT_ssif_dma_rx */
    I2S2_DMA_TX_IRQn            = 336,  /* Interrupt ID:336, INT_ssif_dma_tx */
    I2S2_DMA_RT_IRQn            = 337,  /* Interrupt ID:337, INT_ssif_dma_rt */
    I2S3_INT_REQ_IRQn           = 338,  /* Interrupt ID:338, INT_ssif_int_req */
    I2S3_DMA_RX_IRQn            = 339,  /* Interrupt ID:339, INT_ssif_dma_rx */
    I2S3_DMA_TX_IRQn            = 340,  /* Interrupt ID:340, INT_ssif_dma_tx */
    I2S3_DMA_RT_IRQn            = 341,  /* Interrupt ID:341, INT_ssif_dma_rt */
    SRC0_DMA_IDEI_PLS_IRQn      = 342,  /* Interrupt ID:342, intdma_src_idei_pls_n */
    SRC0_DMA_ODFI_PLS_IRQn      = 343,  /* Interrupt ID:343, intdma_src_odfi_pls_n */
    SRC0_REQ_CEF_IRQn           = 344,  /* Interrupt ID:344, intreq_src_cef_n */
    SRC0_REQ_UDF_IRQn           = 345,  /* Interrupt ID:345, intreq_src_udf_n */
    SRC0_REQ_OVF_IRQn           = 346,  /* Interrupt ID:346, intreq_src_ovf_n */
    ADC_SM_INTAD_IRQn           = 347,  /* Interrupt ID:347, INTAD */
    I2C0_RI_P_IRQn              = 348,  /* Interrupt ID:348, ri_p */
    I2C0_TI_P_IRQn              = 349,  /* Interrupt ID:349, ti_p */
    I2C0_TEI_P_IRQn             = 350,  /* Interrupt ID:350, tei_p */
    I2C0_NAKI_P_IRQn            = 351,  /* Interrupt ID:351, naki_p */
    I2C0_SPI_P_IRQn             = 352,  /* Interrupt ID:352, spi_p */
    I2C0_STI_P_IRQn             = 353,  /* Interrupt ID:353, sti_p */
    I2C0_ALI_P_IRQn             = 354,  /* Interrupt ID:354, ali_p */
    I2C0_TMOI_P_IRQn            = 355,  /* Interrupt ID:355, tmoi_p */
    I2C1_RI_P_IRQn              = 356,  /* Interrupt ID:356, ri_p */
    I2C1_TI_P_IRQn              = 357,  /* Interrupt ID:357, ti_p */
    I2C1_TEI_P_IRQn             = 358,  /* Interrupt ID:358, tei_p */
    I2C1_NAKI_P_IRQn            = 359,  /* Interrupt ID:359, naki_p */
    I2C1_SPI_P_IRQn             = 360,  /* Interrupt ID:360, spi_p */
    I2C1_STI_P_IRQn             = 361,  /* Interrupt ID:361, sti_p */
    I2C1_ALI_P_IRQn             = 362,  /* Interrupt ID:362, ali_p */
    I2C1_TMOI_P_IRQn            = 363,  /* Interrupt ID:363, tmoi_p */
    I2C2_RI_P_IRQn              = 364,  /* Interrupt ID:364, ri_p */
    I2C2_TI_P_IRQn              = 365,  /* Interrupt ID:365, ti_p */
    I2C2_TEI_P_IRQn             = 366,  /* Interrupt ID:366, tei_p */
    I2C2_NAKI_P_IRQn            = 367,  /* Interrupt ID:367, naki_p */
    I2C2_SPI_P_IRQn             = 368,  /* Interrupt ID:368, spi_p */
    I2C2_STI_P_IRQn             = 369,  /* Interrupt ID:369, sti_p */
    I2C2_ALI_P_IRQn             = 370,  /* Interrupt ID:370, ali_p */
    I2C2_TMOI_P_IRQn            = 371,  /* Interrupt ID:371, tmoi_p */
    I2C3_RI_P_IRQn              = 372,  /* Interrupt ID:372, ri_p */
    I2C3_TI_P_IRQn              = 373,  /* Interrupt ID:373, ti_p */
    I2C3_TEI_P_IRQn             = 374,  /* Interrupt ID:374, tei_p */
    I2C3_NAKI_P_IRQn            = 375,  /* Interrupt ID:375, naki_p */
    I2C3_SPI_P_IRQn             = 376,  /* Interrupt ID:376, spi_p */
    I2C3_STI_P_IRQn             = 377,  /* Interrupt ID:377, sti_p */
    I2C3_ALI_P_IRQn             = 378,  /* Interrupt ID:378, ali_p */
    I2C3_TMOI_P_IRQn            = 379,  /* Interrupt ID:379, tmoi_p */
    SCIF0_RERR_IRQn             = 380,  /* Interrupt ID:380, ub1_rerr_n */
    SCIF0_BRK_IRQn              = 381,  /* Interrupt ID:381, ub1_brk_n */
    SCIF0_RXI_IRQn              = 382,  /* Interrupt ID:382, ub1_rxi_n */
    SCIF0_TXI_IRQn              = 383,  /* Interrupt ID:383, ub1_txi_n */
    SCIF0_TEI_DRI_IRQn          = 384,  /* Interrupt ID:384, ub1_tei_dri_n */
    SCIF1_RERR_IRQn             = 385,  /* Interrupt ID:385, ub1_rerr_n */
    SCIF1_BRK_IRQn              = 386,  /* Interrupt ID:386, ub1_brk_n */
    SCIF1_RXI_IRQn              = 387,  /* Interrupt ID:387, ub1_rxi_n */
    SCIF1_TXI_IRQn              = 388,  /* Interrupt ID:388, ub1_txi_n */
    SCIF1_TEI_DRI_IRQn          = 389,  /* Interrupt ID:389, ub1_tei_dri_n */
    SCIF2_RERR_IRQn             = 390,  /* Interrupt ID:390, ub1_rerr_n */
    SCIF2_BRK_IRQn              = 391,  /* Interrupt ID:391, ub1_brk_n */
    SCIF2_RXI_IRQn              = 392,  /* Interrupt ID:392, ub1_rxi_n */
    SCIF2_TXI_IRQn              = 393,  /* Interrupt ID:393, ub1_txi_n */
    SCIF2_TEI_DRI_IRQn          = 394,  /* Interrupt ID:394, ub1_tei_dri_n */
    SCIF3_RERR_IRQn             = 395,  /* Interrupt ID:395, ub1_rerr_n */
    SCIF3_BRK_IRQn              = 396,  /* Interrupt ID:396, ub1_brk_n */
    SCIF3_RXI_IRQn              = 397,  /* Interrupt ID:397, ub1_rxi_n */
    SCIF3_TXI_IRQn              = 398,  /* Interrupt ID:398, ub1_txi_n */
    SCIF3_TEI_DRI_IRQn          = 399,  /* Interrupt ID:399, ub1_tei_dri_n */
    SCIF4_RERR_IRQn             = 400,  /* Interrupt ID:400, ub1_rerr_n */
    SCIF4_BRK_IRQn              = 401,  /* Interrupt ID:401, ub1_brk_n */
    SCIF4_RXI_IRQn              = 402,  /* Interrupt ID:402, ub1_rxi_n */
    SCIF4_TXI_IRQn              = 403,  /* Interrupt ID:403, ub1_txi_n */
    SCIF4_TEI_DRI_IRQn          = 404,  /* Interrupt ID:404, ub1_tei_dri_n */
    SCI0_ERI_IRQn               = 405,  /* Interrupt ID:405, sc_eri_n */
    SCI0_RXI_IRQn               = 406,  /* Interrupt ID:406, sc_rxi_n */
    SCI0_TXI_IRQn               = 407,  /* Interrupt ID:407, sc_txi_n */
    SCI0_TEI_IRQn               = 408,  /* Interrupt ID:408, sc_tei_n */
    SCI1_ERI_IRQn               = 409,  /* Interrupt ID:409, sc_eri_n */
    SCI1_RXI_IRQn               = 410,  /* Interrupt ID:410, sc_rxi_n */
    SCI1_TXI_IRQn               = 411,  /* Interrupt ID:411, sc_txi_n */
    SCI1_TEI_IRQn               = 412,  /* Interrupt ID:412, sc_tei_n */
    RSPI0_RX_IRQn               = 413,   /* Interrupt ID:413, sp_rxint_n */
    RSPI0_TX_IRQn               = 414,   /* Interrupt ID:414, sp_txint_n */
    RSPI0_ERR_IRQn              = 415,   /* Interrupt ID:415, sp_errint_n */
    RSPI1_RX_IRQn               = 416,   /* Interrupt ID:416, sp_rxint_n */
    RSPI1_TX_IRQn               = 417,   /* Interrupt ID:417, sp_txint_n */
    RSPI1_ERR_IRQn              = 418,   /* Interrupt ID:418, sp_errint_n */
    RSPI2_RX_IRQn               = 419,   /* Interrupt ID:419, sp_rxint_n */
    RSPI2_TX_IRQn               = 420,   /* Interrupt ID:420, sp_txint_n */
    RSPI2_ERR_IRQn              = 421,   /* Interrupt ID:421, sp_errint_n */
    CANFD_CHERR0_IRQn           = 422,   /* Interrupt ID:422, can_cherr_int[0]  */
    CANFD_CHERR1_IRQn           = 423,   /* Interrupt ID:423, can_cherr_int[1] */
    CANFD_COMFRX0_IRQn          = 424,   /* Interrupt ID:424, can_comfrx_int[0]  */
    CANFD_COMFRX1_IRQn          = 425,   /* Interrupt ID:425, can_comfrx_int[1] */
    CANFD_GLERR_IRQn            = 426,   /* Interrupt ID:426, can_glerr_int  */
    CANFD_RXF_IRQn              = 427,   /* Interrupt ID:427, can_rxf_int  */
    CANFD_TX0_IRQn              = 428,   /* Interrupt ID:428, can_tx_int[0]  */
    CANFD_TX1_IRQn              = 429,   /* Interrupt ID:429, can_tx_int[1] */
    TSIPG_WRRDYB1_IRQn          = 430,   /* Interrupt ID:430, WRRDYB_1_G */
    TSIPG_WRRDYB0_IRQn          = 431,   /* Interrupt ID:431, WRRDYB_0_G */
    TSIPG_WRRDYB4_IRQn          = 432,   /* Interrupt ID:432, WRRDYB_4_G */
    TSIPG_RDRDYB1_IRQn          = 433,   /* Interrupt ID:433, RDRDYB_1_G */
    TSIPG_RDRDYB0_IRQn          = 434,   /* Interrupt ID:434, RDRDYB_0_G */
    TSIPG_ROM_OK_IRQn           = 435,   /* Interrupt ID:435, ROM_OK_G */
    TSIPG_LONG_PLGB_IRQn        = 436,   /* Interrupt ID:436, LONG_PLGB_G */
    TSIPG_PROC_BUSYB_IRQn       = 437,   /* Interrupt ID:437, PROC_BUSYB_G */
    TSIPG_INTEGRATE_RDRDYB_IRQn = 438,   /* Interrupt ID:438, INTEGRATE_RDRDYB_G */
    TSIPG_INTEGRATE_WRRDYB_IRQn = 439,   /* Interrupt ID:439, INTEGRATE_WRRDYB_G */
                                         /* Interrupt ID:440, Reserved */
                                         /* Interrupt ID:441, Reserved */
                                         /* Interrupt ID:442, Reserved */
                                         /* Interrupt ID:443, Reserved */
    GPIO_TINT0_IRQn             = 444,   /* Interrupt ID:444, TINT0 */
    GPIO_TINT1_IRQn             = 445,   /* Interrupt ID:445, TINT1 */
    GPIO_TINT2_IRQn             = 446,   /* Interrupt ID:446, TINT2 */
    GPIO_TINT3_IRQn             = 447,   /* Interrupt ID:447, TINT3 */
    GPIO_TINT4_IRQn             = 448,   /* Interrupt ID:448, TINT4 */
    GPIO_TINT5_IRQn             = 449,   /* Interrupt ID:449, TINT5 */
    GPIO_TINT6_IRQn             = 450,   /* Interrupt ID:450, TINT6 */
    GPIO_TINT7_IRQn             = 451,   /* Interrupt ID:451, TINT7 */
    GPIO_TINT8_IRQn             = 452,   /* Interrupt ID:452, TINT8 */
    GPIO_TINT9_IRQn             = 453,   /* Interrupt ID:453, TINT9 */
    GPIO_TINT10_IRQn            = 454,   /* Interrupt ID:454, TINT10 */
    GPIO_TINT11_IRQn            = 455,   /* Interrupt ID:455, TINT11 */
    GPIO_TINT12_IRQn            = 456,   /* Interrupt ID:456, TINT12 */
    GPIO_TINT13_IRQn            = 457,   /* Interrupt ID:457, TINT13 */
    GPIO_TINT14_IRQn            = 458,   /* Interrupt ID:458, TINT14 */
    GPIO_TINT15_IRQn            = 459,   /* Interrupt ID:459, TINT15 */
    GPIO_TINT16_IRQn            = 460,   /* Interrupt ID:460, TINT16 */
    GPIO_TINT17_IRQn            = 461,   /* Interrupt ID:461, TINT17 */
    GPIO_TINT18_IRQn            = 462,   /* Interrupt ID:462, TINT18 */
    GPIO_TINT19_IRQn            = 463,   /* Interrupt ID:463, TINT19 */
    GPIO_TINT20_IRQn            = 464,   /* Interrupt ID:464, TINT20 */
    GPIO_TINT21_IRQn            = 465,   /* Interrupt ID:465, TINT21 */
    GPIO_TINT22_IRQn            = 466,   /* Interrupt ID:466, TINT22 */
    GPIO_TINT23_IRQn            = 467,   /* Interrupt ID:467, TINT23 */
    GPIO_TINT24_IRQn            = 468,   /* Interrupt ID:468, TINT24 */
    GPIO_TINT25_IRQn            = 469,   /* Interrupt ID:469, TINT25 */
    GPIO_TINT26_IRQn            = 470,   /* Interrupt ID:470, TINT26 */
    GPIO_TINT27_IRQn            = 471,   /* Interrupt ID:471, TINT27 */
    GPIO_TINT28_IRQn            = 472,   /* Interrupt ID:472, TINT28 */
    GPIO_TINT29_IRQn            = 473,   /* Interrupt ID:473, TINT29 */
    GPIO_TINT30_IRQn            = 474,   /* Interrupt ID:474, TINT30 */
    GPIO_TINT31_IRQn            = 475,   /* Interrupt ID:475, TINT31 */
                                         /* Interrupt ID:476, Reserved */
                                         /* Interrupt ID:477, Reserved */
                                         /* Interrupt ID:478, Reserved */
                                         /* Interrupt ID:479, Reserved */
} IRQn_Type;

/** @} (end addtogroup BSP_MPU_RZG2L) */

#endif
